### PR TITLE
Added FACS Quest Pro Parameters

### PR DESCRIPTION
**Pull request by dfgHiatus**
Added eyebrow parameters, will add face parameters in a later commit

### CODE REVIEW

**Comment by Adjerry91** [comment]
combined squint is not named correcly. Squint does not involve the eyebrows. Change EyesSquint

**Comment by dfgHiatus** [comment]
> Going to close this until "quest-pro-params" is fully tested. In the meantime, here is the proposed system for adding arbitrary facial expressions:

Currently, VRCFT's mouth shapes are tied down to SRanipal. While this hasn't been an issue historically (IE ARKit), the Quest Pro's new FACS system has expressions that don't necessarily map over. These include:

```
BrowLowererL,
BrowLowererR,
CheekRaiserL,
CheekRaiserR,
ChinRaiserB,
ChinRaiserT,
DimplerL,
DimplerR,
InnerBrowRaiserL,
InnerBrowRaiserR,
LipFunnelerLB,
LipFunnelerLT,
LipFunnelerRB,
LipFunnelerRT,
LipPressorL,
LipPressorR,
LipPuckerL, // Mouth Pout but not combined
LipPuckerR, // Mouth Pout but not combined
LipStretcherL,
LipStretcherR,
LipSuckLB, // Cheek Suck but not combined
LipSuckLT, // Cheek Suck but not combined
LipSuckRB, // Cheek Suck but not combined
LipSuckRT, // Cheek Suck but not combined
LipTightenerL,
LipTightenerR,
LowerLipDepressorL,
LowerLipDepressorR,
NoseWrinklerL,
NoseWrinklerR,
OuterBrowRaiserL,
OuterBrowRaiserR,
```

To address this, we first need to consider how VRCFT updates mouth expressions:

```
public float[] LatestShapes = new float[SRanipal_Lip_v2.WeightingCount];
...
for (int i = 0; i < WeightingCount; ++i)
{
    Weightings[(LipShape_v2)i] = LipData.prediction_data.blend_shape_weight[i];
    Weightings[(VRCFTLipShape)i] = LipData.prediction_data.blend_shape_weight[i];
}
```

Where `WeightingCount = 37`. Consider the following:

```
public float[] LatestShapes = new float[(int) VRCFTLipShape.Max + 1];
```

Where `VRCFTLipShape` refers to a complete list of facial expressions. By expressly NOT updating the above for loop, VRCFT will only update the "core" expressions as intended, and custom shapes can be selectively updated by module developers. Let me know your thoughts on this, the names are mere placeholder at which point they will be updated.

**Comment by dfgHiatus** [comment]
Reopening as yesterday's tests were successful

**Review by Adjerry91 — COMMENTED** [review]
what is EyeBrow structure in UnifiedTrackingData.cs? there is no innnerBrowDown it would be browDown

**Comment by regzo2** [comment]
@dfgHiatus I'm going to add some Combined shapes to your commit if you don't mind!

**Comment by regzo2** [comment]
I also want to add that the exclusion of a lot of the tracking params has been a problem for ARKit, it's just that now there's a bigger push to have these because of the Quest Pro.

**Comment by regzo2** [comment]
Looking over the base shapes, it looks like there are several duplicates from the Expanded expressions that could map directly into SRanipal shapes. I also expanded out the comments from UnifiedExpression that I would like to be considered.
```
JawRight, // +JawX
JawLeft, // -JawX
JawForward, // Jaw Forward
JawOpen, // Jaw Drop
MouthApeShape, // Jaw Open + Mouth Closed, does not seem to map properly on (Quest Pro)
MouthUpperRight, // +MouthUpper
MouthUpperLeft, // -MouthUpper
MouthLowerRight, // +MouthLower
MouthLowerLeft, // -MouthLower
MouthUpperOverturn, // Lip Funneller Top
MouthLowerOverturn, // Lip Funneller Bottom
MouthPout, // Driven directly by SRanipal, could be driven with Lip Tightener + Lip Pucker. Could just as well be a combined parameter.
MouthSmileRight, // +SmileSadRight // Lip Corner Raiser Right
MouthSmileLeft, // +SmileSadLeft // Lip Corner Raiser Left
MouthSadRight, // -SmileSadRight // Lip Corner Depressor Right
MouthSadLeft, // -SmileSadLeft // Lip Corner Depressor Left
CheekPuffRight,
CheekPuffLeft,
CheekSuck, // Driven directly by SRanipal, could be driven by the average of Cheek Suck Left and Cheek Suck Right (seems to be excluded from the extra shapes)
MouthUpperUpRight, // UpperLipRaiserR
MouthUpperUpLeft, // UpperLipRaiserL
MouthLowerDownRight, // LowerLipDepressorR
MouthLowerDownLeft, // LowerLipDepressorL
MouthUpperInside,
MouthLowerInside,
MouthLowerOverlay,
TongueLongStep1,
TongueLongStep2,
TongueDown, // -TongueY
TongueUp, // +TongueY
TongueRight, // +TongueX
TongueLeft, // -TongueX
TongueRoll,
TongueUpLeftMorph,
TongueUpRightMorph,
TongueDownLeftMorph,
TongueDownRightMorph,
SRanipalMax,

CheekRaiserL,
CheekRaiserR,
ChinRaiserB,
ChinRaiserT,
DimplerL,
DimplerR,
LipFunnelerLB, // Mouth Lower Overturn Bottom Left but uncombined
LipFunnelerLT, // Mouth Lower Overturn Top Left but uncombined
LipFunnelerRB, // Mouth Lower Overturn Bottom Right but uncombined
LipFunnelerRT, // Mouth Lower Overturn Top Right but uncombined
LipPressorL,
LipPressorR,
LipPuckerL, // Mouth Pout but not combined, combines with Lip Tightener to form Pout
LipPuckerR, // Mouth Pout but not combined, combines with Lip Tightener to form Pout
LipStretcherL,
LipStretcherR,
LipSuckLB, // Cheek Suck but not combined
LipSuckLT, // Cheek Suck but not combined
LipSuckRB, // Cheek Suck but not combined
LipSuckRT, // Cheek Suck but not combined
LipTightenerL, // Mouth Pout but not combined, combines with Lip Pucker to form Pout
LipTightenerR, // Mouth Pout but not combined, combines with Lip Pucker to form Pout
LowerLipDepressorL, // Maps to Mouth Lower Down Left, this is most likely a duplicate shape
LowerLipDepressorR, // Maps to Mouth Lower Down Right, this is most likely a duplicate shape
NoseWrinklerL,
NoseWrinklerR,
```
Also I noticed that you have a comment in UnifiedExpression pertaining to possible mapping the SRanipal set to the new shapes, I like the idea! It might be a good idea to have an extra UI tab for Tracking Modules to be able to let the user map these (especially for something like Eyebrow emulation from SRanipal).

We should settle the base shapes before continuing with some of the Combined shapes

**Comment by dfgHiatus** [comment]
> what is EyeBrow structure in UnifiedTrackingData.cs? there is no innnerBrowDown it would be browDown

This is by design, while FACS does not have inner/outer brow down I decided it would be in our interest to include it, for the sake for consistency and for future proof-edness.

**Comment by regzo2** [comment]
Seems like the Cheek_Suck_L and R is definitely missing from the expanded set, just had a look over from the Meta FACS set

**Comment by Adjerry91** [comment]
> > what is EyeBrow structure in UnifiedTrackingData.cs? there is no innnerBrowDown it would be browDown
> 
> This is by design, while FACS does not have inner/outer brow down I decided it would be in our interest to include it, for the sake for consistency and for future proof-edness.

The browInnerUp and browOuterUp control the angle of the brows. browDown controls the height which I do not see that being split ever.

**Comment by dfgHiatus** [comment]
Master branch got beaned, I'll get this back up

**Comment by dfgHiatus** [comment]
The new branch is here: https://github.com/dfgHiatus/VRCFaceTracking/tree/quest-pro-params

**Comment by Adjerry91** [comment]
Work on unified expressions overhaul will be cover on pull request [109](https://github.com/benaclejames/VRCFaceTracking/pull/109) for expression overhaul. Closing this pull request

**Pull request closed without merging**
