### PR TITLE
Make module folder move work across volumes

### PR DESCRIPTION
**Pull request by orcinus**
Fix for issue #162 

Directory.Move does not work across volumes, meaning having your Temp folder not on the same drive as your User folder will cause module installation to fail.

This uses a non-recursive folder-copy / delete appropriated for SO instead of Directory.Move.

### CODE REVIEW

**Comment by orcinus** [comment]
Sorry about the whitespace crap, that was the VS linter's doing.

**Comment by benaclejames** [comment]
Sorry for the delay on this, been super busy implementing the new oscquery spec as per vrchat's open beta. I actually made & committed a less-verbose fix for this on the day but forgot to actually push it. Thanks for your PR and sorry I didn't see it sooner

**Comment by orcinus** [comment]
No worries, important thing is it's fixed :)

**Comment by orcinus** [comment]
This still hasn't been integrated into a release?

**Pull request closed without merging**
